# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentArea', '0004_addresses_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_address_from', models.DateField()),
                ('date_address_to', models.DateField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentArea.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField()),
                ('school_principle', models.CharField(max_length=200)),
                ('other_school_details', models.TextField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentArea.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Studen_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('address_details', models.TextField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentArea.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjact_name', models.TextField()),
            ],
        ),
    ]
