# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentArea', '0005_patrentaddress_schools_studen_address_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentArea.Parents')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentArea.Students')),
            ],
        ),
        migrations.RenameModel(
            old_name='Studen_Address',
            new_name='Student_Address',
        ),
    ]
